### ISSUE TITLE
TO-DO stuff

### ISSUE THREAD

**Issue by Franccisco** [Franccisco/code-jam-6#20]
- [ ] Keyboard, Plugboard and Rotors should have the same background color, or something more consistent.
- [ ] Change Rotors (+) and (-) buttons for images
- [ ] Link front-end and back-end

**Comment by YoomamaFTW** [comment]
Are there methods for me to execute stuff for "Link front-end and back-end?"

**Comment by Franccisco** [comment]
@YoomamaFTW yes, your help is welcome! By now, PaperScreen is the only left to be merged (I'll review that). We have to talk about how to link both front-end and back-end.
